name: Terraform Code
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}

    # defaults:
    #   run:
    #     shell: bash
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2

      # Runs a single command using the runners shell
      - name: 'Terraform init'
        id: init
        run: terraform init          

      - name: 'Terraform plan'
        id: plan
        run: terraform plan
                    
      - name: 'Terraform apply'
        id: apply
        run: terraform apply -auto-approve 
          
