name: 'Terraform Deployment'
on:
  push:
    branches: [ githubAction ]

permissions:
  id-token: write
  contents: read

env:
  ARM_CLIENT_ID: "${{ secrets.AZURE_AD_CLIENT_ID }}"
  ARM_SUBSCRIPTION_ID: "${{ secrets.AZURE_AD_SUBSCRIPTION_ID }}"
  ARM_TENANT_ID: "${{ secrets.AZURE_AD_TENANT_ID }}"

jobs:
  build:
    runs-on: self-hosted
    environment:
      name: secretForTerraform
    steps:
      - name: 'Checkout repo'
        uses: actions/checkout@v3

      - name: 'Install Terraform'
        uses: little-core-labs/install-terraform@v2.0.0
        with:
          version: 0.13.4

      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_AD_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_AD_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_AD_SUBSCRIPTION_ID }}
          enable-AzPSSession: true 

      - name: 'Terraform init'
        id: init
        run: terraform init
        continue-on-error: true 

      - name: Terraform plan
        id: plan
        run: terraform plan
        continue-on-error: true
                    
      - name: Terraform Apply
        id: apply
        run: terraform apply --auto-approve
        continue-on-error: true 

      - name: 'Terraform destroy'
        id: destroy
        run: terraform destroy --auto-approve
        continue-on-error: true
          
