name: 'Terraform Deployment'
on:
  push:
    branches: [ githubAction ]

permissions:
  id-token: write
  contents: read

env:
  ARM_CLIENT_ID: "${{ secrets.AZURE_AD_CLIENT_ID }}"
  ARM_SUBSCRIPTION_ID: "${{ secrets.AZURE_AD_SUBSCRIPTION_ID }}"
  ARM_TENANT_ID: "${{ secrets.AZURE_AD_TENANT_ID }}"

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: secretForTerraform
    steps:
      - name: 'Checkout repo'
        uses: actions/checkout@v3

      - name: 'Install Terraform'
        uses: little-core-labs/install-terraform@v2.0.0
        with:
          version: 0.13.4

      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_AD_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_AD_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_AD_SUBSCRIPTION_ID }}
          enable-AzPSSession: true 

      - name: 'Terraform init'
        id: init
        uses: hashicorp/terraform-github-actions/init@v0.4.0

      - name: Terraform format check
        id: fmt
        uses: hashicorp/terraform-github-actions/fmt@v0.3.7
        continue-on-error: true          

      - name: Terraform plan
        id: plan
        uses: hashicorp/terraform-github-actions/plan@v0.4.0
        continue-on-error: true
                    
      - name: Terraform Apply
        id: apply
        uses: hashicorp/terraform-github-actions/apply@v0.4.0
        continue-on-error: true 

      - name: 'Terraform destroy'
        id: destroy
        run: terraform destroy -auto-approve
          
