name: Terraform Code
on:
  push:
    branches: [ main ]

permissions:
  id-token: write
  contents: read

env:
  ARM_CLIENT_ID: "${{ secrets.AZURE_AD_CLIENT_ID }}"
  ARM_SUBSCRIPTION_ID: "${{ secrets.AZURE_AD_SUBSCRIPTION_ID }}"
  ARM_TENANT_ID: "${{ secrets.AZURE_AD_TENANT_ID }}"

jobs:
  build:
    runs-on: githubActionRunner
    environment:
      name: secretForTerraform
    steps:
      - uses: actions/checkout@v3
      - name: run
        run: echo "${{ secrets.AZURE_AD_CLIENT_ID }}"
      - name: Install Terraform
        uses: little-core-labs/install-terraform@v2.0.0
        with:
          version: 0.13.4
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_AD_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_AD_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_AD_SUBSCRIPTION_ID }}
          enable-AzPSSession: true 
      - name: 'Terraform init'
        id: init
        run: terraform init          

      - name: 'Terraform plan'
        id: plan
        run: terraform plan
                    
      - name: 'Terraform apply'
        id: apply
        run: terraform apply -auto-approve 

      - name: 'Terraform destroy'
        id: destroy
        run: terraform destroy -auto-approve
          
