name: Terraform Code
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: "6bb1a01d-521f-454b-a806-1a57acbab266"
      ARM_CLIENT_SECRET: "dhU8Q~-qvhuqcYLWeqqWndFVSxD1rIjhQgJR-bQA"
      ARM_SUBSCRIPTION_ID: "4cedc5dd-e3ad-468d-bf66-32e31bdb9148"
      ARM_TENANT_ID: "3617ef9b-98b4-40d9-ba43-e1ed6709cf0d"
      enable-AzPSSession: true

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_AD_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
          subscription-id: ${{ secrets.AZURE_AD_SUBSCRIPTION_ID}}
          enable-AzPSSession: true 

      # - name : Azure Login
      #   run: az login -u ${{secrets.USERNAME}} -p ${{secrets.PASSWORD}}

      - name: 'Terraform init'
        id: init
        run: terraform init          

      - name: 'Terraform plan'
        id: plan
        run: terraform plan
                    
      - name: 'Terraform apply'
        id: apply
        run: terraform apply -auto-approve 
          
